### ISSUE TITLE
Prime number are not prime

### ISSUE THREAD

**Issue by giuseppeM99** [wrxck/mattata#18]
So, prime numbers are not prime?
Well, prime plugin don't work at all.
I've tested all the prime numbers < 101 and the result was that only 1, 2 and 3 are prime, and 1 is not a prime number

**Comment by wrxck** [comment]
Hm. I'll take a look and get back to you.

**Comment by wrxck** [comment]
Fixed this issue and applied changes to @mattatabot. Will include this patch in the next release.
