### ISSUE TITLE
Add LastFM

### ISSUE THREAD

**Issue by Joshua1337** [wrxck/mattata#2]
Hi, can you add a LastFM plugin and make it post like that:

![image](https://cloud.githubusercontent.com/assets/3116843/18885513/43247164-84ec-11e6-9f84-604fab2c63d6.png)

Would be awesome 😎

**Comment by wrxck** [comment]
Hi Joshua, I'm going to port the plugin from otouto and go from there.

**Comment by wrxck** [comment]
added hacktoberfest label

**Comment by wrxck** [comment]
Implemented. If anything else can be done to improve it please let me know and re-open this issue :)
