### ISSUE TITLE
/isup protocol detection is faulty

### ISSUE THREAD

**Issue by Zenexer** [wrxck/mattata#23]
Examples:

| Input                    | Expected           | Actual                   |
|:-------------------------|:-------------------|:-------------------------|
| `http.com`               | `http://http.com`  | `http.com`               |
| `https.com`              | `http://https.com` | `https://https.com`      |
| `httpmoo://example.com/` | (error)            | `httpmoo://example.com/` |

**Comment by wrxck** [comment]
See #22
