### ISSUE TITLE
Installation ubuntu

### ISSUE THREAD

**Issue by koodoxz** [wrxck/mattata#50]
Hi 

Just try to installing in ubuntu from installation directory but found this one : 

[Info] Installing openssl...
sudo: luarocks-5.3: command not found

and after that, cant start the bot
 
thanks

**Comment by koodoxz** [comment]
Solved

by manual installing lua5-3 from the source

thanks

**Comment by TheWildBear** [comment]
@koodoxz oh there's a mistake in the installer! That's not your fault that it isn't working. I'll see if I have some time the next days to fix the issue. Thanks for opening the issue!
