### ISSUE TITLE
./launch.sh: 7: ./launch.sh: lua5.3: not found

### ISSUE THREAD

**Issue by NinjaTurtle007** [wrxck/mattata#70]
Upon launch of ./launch.sh I get this

> ./launch.sh: 7: ./launch.sh: lua5.3: not found

I installed the bot with the ubuntu command (with sudo)
in the config file I only entered the bot token and changed the file name to configuration.lua

**Comment by kh-3379** [comment]
Me too?
Why?
Please answer me

**Comment by kh-3379** [comment]
> Connection

 error [connection refused]
lua: /usr/local/share/lua/5.3/telegram-bot-lua/core.lua:32: attempt to index a boolean value (field 'info')
stack traceback:
	/usr/local/share/lua/5.3/telegram-bot-lua/core.lua:32: in function 'telegram-bot-lua.core.configure'
	./mattata.lua:24: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
mattata has 

> stopped!

**Comment by kh-3379** [comment]
### please help me

Connection error [connection refused]
lua: /usr/local/share/lua/5.3/telegram-bot-lua/core.lua:32: attempt to index a boolean value (field 'info')
stack traceback:
	/usr/local/share/lua/5.3/telegram-bot-lua/core.lua:32: in function 'telegram-bot-lua.core.configure'
	./mattata.lua:24: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
mattata has stopped!
###  why??

**Comment by wrxck** [comment]
Are you sure the bot token is correct @kh-3379

**Comment by wrxck** [comment]
Also, @NinjaTurtle007 please try changing all instances of "lua5.3" to "lua" in `launch.sh`

**Comment by wrxck** [comment]
(As a temporary fix until I get around to applying a patch)

**Comment by hesamg96** [comment]
im having the same problem here
