### ISSUE TITLE
/time not working

### ISSUE THREAD

**Issue by joostlek** [wrxck/mattata#9]
mattata:
[2016-10-04 08:56:02]
mattatabot: ./socket/http.lua:240: attempt to index local 'reqt' (a nil value)
38144652: /time

**Comment by wrxck** [comment]
Yeah I'll sort that out later, when I get home (in the meantime I can upload a patch, it just won't be applied to @mattatabot until later).

**Comment by wrxck** [comment]
Fixed - turns out I forgot to change `configuration.time_api` to `configuration.apis.time` XD
